server:
  http_listen_port: 3100
  grpc_listen_port: 0

clients:
  - url: http://{{ loki_host }}:{{ loki_port }}/loki/api/v1/push

positions:
  filename: /opt/promtail/positions.yaml

scrape_configs:
  - job_name: ec2-logs
    ec2_sd_configs:
      - region: us-west-2
        role_arn: promtail_iam_role
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
        action: replace
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
        action: replace
      - source_labels: [__meta_ec2_availability_zone]
        target_label: zone
        action: replace
      - action: replace
        replacement: /home/ustock/reactor/reactor.log.out
        target_label: __path__
      - action: replace
        replacement: /home/ustock/setup.log
        target_label: __path__
      - source_labels: [__meta_ec2_private_dns_name]
        regex: "(.*)"
        target_label: __host__
